\connect jingyi_icis_db;

INSERT INTO patient_records (
    id, his_mrn, his_patient_id, his_index_id, his_patient_serial_number,
    his_admission_count, his_admission_time, his_admission_diagnosis, his_bed_number,
    icu_manual_entry, icu_manual_entry_account_id, icu_name, icu_gender, icu_date_of_birth,
    height, weight, weight_type, weight_ibw, blood_type, blood_rh, past_medical_history,
    allergies, phone, home_phone, home_address, document_type, id_card_number, nation,
    native_place, occupation, marital_status, emergency_contact_name, emergency_contact_relation,
    emergency_contact_phone, emergency_contact_address, payment_method, insurance_type,
    insurance_number, medical_card_number, is_vip_patient, bed_number_str, wristband_location,
    patient_pose, nursing_care_level, illness_severity_level, diet_type, isolation_precaution,
    chief_complaint, dept_id, dept_name, ward_code, ward_name, attending_doctor_id,
    primary_care_doctor_id, admitting_doctor_id, responsible_nurse_id, admission_source_dept_name,
    admission_source_dept_id, admission_type, is_planned_admission, unplanned_admission_reason,
    admission_status, admission_time, admission_edit_time, admitting_account_id, diagnosis_time,
    diagnosis, diagnosis_code, diagnosis_tcm, diagnosis_tcm_code, diagnosis_type, diagnosis_account_id,
    discharged_type, discharged_death_time, discharged_hospital_exit_time, discharged_diagnosis,
    discharged_dept_name, discharged_dept_id, discharge_time, discharge_edit_time, discharging_account_id,
    created_at
) VALUES 
    (1, 'mrn1', 'hisPatientId1', 'hisIndexId1', 'hisPatientSerialNumber1',
    1, now(), 'hisAdmissionDiagnosis1', 'hisBedNumber1',
    false, '', 'icuName1', 1, now(),
    1.76, 65.02, 'weightType1', 'weightIbw1', 'bloodType1', 'bloodRh1', 'pastMedicalHistory1',
    'allergies1', 'phone1', 'homePhone1', 'homeAddress1', 'documentType1', 'idCardNumber1', 'nation1',
    'nativePlace1', 'occupation1', 0, 'emergencyContactName1', 'emergencyContactRelation1',
    'emergencyContactPhone1', 'emergencyContactAddress1', 'paymentMethod1', 'insuranceType1',
    'insuranceNumber1', 'medicalCardNumber1', false, 'bed1', 'wristbandLocation1',
    'patientPose1', 'nursingCareLevel1', 'illnessSeverityLevel1', 'dietType1', 'isolationPrecaution1',
    'chiefComplaint1', 'admin', 'deptNameadmin', 'wardCode1', 'wardName1', 'attendingDoctorId1',
    'primaryCareDoctorId1', 'admittingDoctorId1', 'responsibleNurseId1', 'admissionSourceDeptName1',
    'admissionSourceDeptId1', 'admissionType1', true, '',
    0, now(), now(), 'admittingAccountId1', now(),
    'diagnosis1', 'diagnosisCode1', 'diagnosisTcm1', 'diagnosisTcmCode1', 'diagnosisType1', 'diagnosisAccountId1',
    'dischargedType1', now(), now(), 'dischargedDiagnosis1',
    'dischargedDeptName1', 'dischargedDeptId1', now(), now(), 'dischargingAccountId1',
    now()),
    (2, 'mrn2', 'hisPatientId2', 'hisIndexId2', 'hisPatientSerialNumber2',
    1, now(), 'hisAdmissionDiagnosis2', 'hisBedNumber2',
    false, '', 'icuName2', 1, now(),
    1.77, 65.04, 'weightType2', 'weightIbw2', 'bloodType2', 'bloodRh2', 'pastMedicalHistory2',
    'allergies2', 'phone2', 'homePhone2', 'homeAddress2', 'documentType2', 'idCardNumber2', 'nation2',
    'nativePlace2', 'occupation2', 0, 'emergencyContactName2', 'emergencyContactRelation2',
    'emergencyContactPhone2', 'emergencyContactAddress2', 'paymentMethod2', 'insuranceType2',
    'insuranceNumber2', 'medicalCardNumber2', false, 'bed2', 'wristbandLocation2',
    'patientPose2', 'nursingCareLevel2', 'illnessSeverityLevel2', 'dietType2', 'isolationPrecaution2',
    'chiefComplaint2', 'admin', 'deptNameadmin', 'wardCode2', 'wardName2', 'attendingDoctorId2',
    'primaryCareDoctorId2', 'admittingDoctorId2', 'responsibleNurseId2', 'admissionSourceDeptName2',
    'admissionSourceDeptId2', 'admissionType2', true, '',
    0, now(), now(), 'admittingAccountId2', now(),
    'diagnosis2', 'diagnosisCode2', 'diagnosisTcm2', 'diagnosisTcmCode2', 'diagnosisType2', 'diagnosisAccountId2',
    'dischargedType2', now(), now(), 'dischargedDiagnosis2',
    'dischargedDeptName2', 'dischargedDeptId2', now(), now(), 'dischargingAccountId2',
    now()),
    (3, 'mrn3', 'hisPatientId3', 'hisIndexId3', 'hisPatientSerialNumber3',
    1, now(), 'hisAdmissionDiagnosis3', 'hisBedNumber3',
    false, '', 'icuName3', 1, now(),
    1.78, 65.06, 'weightType3', 'weightIbw3', 'bloodType3', 'bloodRh3', 'pastMedicalHistory3',
    'allergies3', 'phone3', 'homePhone3', 'homeAddress3', 'documentType3', 'idCardNumber3', 'nation3',
    'nativePlace3', 'occupation3', 0, 'emergencyContactName3', 'emergencyContactRelation3',
    'emergencyContactPhone3', 'emergencyContactAddress3', 'paymentMethod3', 'insuranceType3',
    'insuranceNumber3', 'medicalCardNumber3', false, 'bed3', 'wristbandLocation3',
    'patientPose3', 'nursingCareLevel3', 'illnessSeverityLevel3', 'dietType3', 'isolationPrecaution3',
    'chiefComplaint3', 'admin', 'deptNameadmin', 'wardCode3', 'wardName3', 'attendingDoctorId3',
    'primaryCareDoctorId3', 'admittingDoctorId3', 'responsibleNurseId3', 'admissionSourceDeptName3',
    'admissionSourceDeptId3', 'admissionType3', true, '',
    0, now(), now(), 'admittingAccountId3', now(),
    'diagnosis3', 'diagnosisCode3', 'diagnosisTcm3', 'diagnosisTcmCode3', 'diagnosisType3', 'diagnosisAccountId3',
    'dischargedType3', now(), now(), 'dischargedDiagnosis3',
    'dischargedDeptName3', 'dischargedDeptId3', now(), now(), 'dischargingAccountId3',
    now()),
    (4, 'mrn4', 'hisPatientId4', 'hisIndexId4', 'hisPatientSerialNumber4',
    1, now(), 'hisAdmissionDiagnosis4', 'hisBedNumber4',
    false, '', 'icuName4', 1, now(),
    1.79, 65.08, 'weightType4', 'weightIbw4', 'bloodType4', 'bloodRh4', 'pastMedicalHistory4',
    'allergies4', 'phone4', 'homePhone4', 'homeAddress4', 'documentType4', 'idCardNumber4', 'nation4',
    'nativePlace4', 'occupation4', 0, 'emergencyContactName4', 'emergencyContactRelation4',
    'emergencyContactPhone4', 'emergencyContactAddress4', 'paymentMethod4', 'insuranceType4',
    'insuranceNumber4', 'medicalCardNumber4', false, 'bed4', 'wristbandLocation4',
    'patientPose4', 'nursingCareLevel4', 'illnessSeverityLevel4', 'dietType4', 'isolationPrecaution4',
    'chiefComplaint4', 'admin', 'deptNameadmin', 'wardCode4', 'wardName4', 'attendingDoctorId4',
    'primaryCareDoctorId4', 'admittingDoctorId4', 'responsibleNurseId4', 'admissionSourceDeptName4',
    'admissionSourceDeptId4', 'admissionType4', true, '',
    0, now(), now(), 'admittingAccountId4', now(),
    'diagnosis4', 'diagnosisCode4', 'diagnosisTcm4', 'diagnosisTcmCode4', 'diagnosisType4', 'diagnosisAccountId4',
    'dischargedType4', now(), now(), 'dischargedDiagnosis4',
    'dischargedDeptName4', 'dischargedDeptId4', now(), now(), 'dischargingAccountId4',
    now()),
    (5, 'mrn5', 'hisPatientId5', 'hisIndexId5', 'hisPatientSerialNumber5',
    1, now(), 'hisAdmissionDiagnosis5', 'hisBedNumber5',
    false, '', 'icuName5', 1, now(),
    1.80, 65.10, 'weightType5', 'weightIbw5', 'bloodType5', 'bloodRh5', 'pastMedicalHistory5',
    'allergies5', 'phone5', 'homePhone5', 'homeAddress5', 'documentType5', 'idCardNumber5', 'nation5',
    'nativePlace5', 'occupation5', 0, 'emergencyContactName5', 'emergencyContactRelation5',
    'emergencyContactPhone5', 'emergencyContactAddress5', 'paymentMethod5', 'insuranceType5',
    'insuranceNumber5', 'medicalCardNumber5', false, 'bed5', 'wristbandLocation5',
    'patientPose5', 'nursingCareLevel5', 'illnessSeverityLevel5', 'dietType5', 'isolationPrecaution5',
    'chiefComplaint5', 'admin', 'deptNameadmin', 'wardCode5', 'wardName5', 'attendingDoctorId5',
    'primaryCareDoctorId5', 'admittingDoctorId5', 'responsibleNurseId5', 'admissionSourceDeptName5',
    'admissionSourceDeptId5', 'admissionType5', true, '',
    0, now(), now(), 'admittingAccountId5', now(),
    'diagnosis5', 'diagnosisCode5', 'diagnosisTcm5', 'diagnosisTcmCode5', 'diagnosisType5', 'diagnosisAccountId5',
    'dischargedType5', now(), now(), 'dischargedDiagnosis5',
    'dischargedDeptName5', 'dischargedDeptId5', now(), now(), 'dischargingAccountId5',
    now()),
    (6, 'mrn6', 'hisPatientId6', 'hisIndexId6', 'hisPatientSerialNumber6',
    1, now(), 'hisAdmissionDiagnosis6', 'hisBedNumber6',
    false, '', 'icuName6', 1, now(),
    1.81, 65.12, 'weightType6', 'weightIbw6', 'bloodType6', 'bloodRh6', 'pastMedicalHistory6',
    'allergies6', 'phone6', 'homePhone6', 'homeAddress6', 'documentType6', 'idCardNumber6', 'nation6',
    'nativePlace6', 'occupation6', 0, 'emergencyContactName6', 'emergencyContactRelation6',
    'emergencyContactPhone6', 'emergencyContactAddress6', 'paymentMethod6', 'insuranceType6',
    'insuranceNumber6', 'medicalCardNumber6', false, 'bed6', 'wristbandLocation6',
    'patientPose6', 'nursingCareLevel6', 'illnessSeverityLevel6', 'dietType6', 'isolationPrecaution6',
    'chiefComplaint6', 'admin', 'deptNameadmin', 'wardCode6', 'wardName6', 'attendingDoctorId6',
    'primaryCareDoctorId6', 'admittingDoctorId6', 'responsibleNurseId6', 'admissionSourceDeptName6',
    'admissionSourceDeptId6', 'admissionType6', true, '',
    0, now(), now(), 'admittingAccountId6', now(),
    'diagnosis6', 'diagnosisCode6', 'diagnosisTcm6', 'diagnosisTcmCode6', 'diagnosisType6', 'diagnosisAccountId6',
    'dischargedType6', now(), now(), 'dischargedDiagnosis6',
    'dischargedDeptName6', 'dischargedDeptId6', now(), now(), 'dischargingAccountId6',
    now()),
    (7, 'mrn7', 'hisPatientId7', 'hisIndexId7', 'hisPatientSerialNumber7',
    1, now(), 'hisAdmissionDiagnosis7', 'hisBedNumber7',
    false, '', 'icuName7', 1, now(),
    1.82, 65.14, 'weightType7', 'weightIbw7', 'bloodType7', 'bloodRh7', 'pastMedicalHistory7',
    'allergies7', 'phone7', 'homePhone7', 'homeAddress7', 'documentType7', 'idCardNumber7', 'nation7',
    'nativePlace7', 'occupation7', 0, 'emergencyContactName7', 'emergencyContactRelation7',
    'emergencyContactPhone7', 'emergencyContactAddress7', 'paymentMethod7', 'insuranceType7',
    'insuranceNumber7', 'medicalCardNumber7', false, 'bed7', 'wristbandLocation7',
    'patientPose7', 'nursingCareLevel7', 'illnessSeverityLevel7', 'dietType7', 'isolationPrecaution7',
    'chiefComplaint7', 'admin', 'deptNameadmin', 'wardCode7', 'wardName7', 'attendingDoctorId7',
    'primaryCareDoctorId7', 'admittingDoctorId7', 'responsibleNurseId7', 'admissionSourceDeptName7',
    'admissionSourceDeptId7', 'admissionType7', true, '',
    0, now(), now(), 'admittingAccountId7', now(),
    'diagnosis7', 'diagnosisCode7', 'diagnosisTcm7', 'diagnosisTcmCode7', 'diagnosisType7', 'diagnosisAccountId7',
    'dischargedType7', now(), now(), 'dischargedDiagnosis7',
    'dischargedDeptName7', 'dischargedDeptId7', now(), now(), 'dischargingAccountId7',
    now()),
    (8, 'mrn8', 'hisPatientId8', 'hisIndexId8', 'hisPatientSerialNumber8',
    1, now(), 'hisAdmissionDiagnosis8', 'hisBedNumber8',
    false, '', 'icuName8', 1, now(),
    1.83, 65.16, 'weightType8', 'weightIbw8', 'bloodType8', 'bloodRh8', 'pastMedicalHistory8',
    'allergies8', 'phone8', 'homePhone8', 'homeAddress8', 'documentType8', 'idCardNumber8', 'nation8',
    'nativePlace8', 'occupation8', 0, 'emergencyContactName8', 'emergencyContactRelation8',
    'emergencyContactPhone8', 'emergencyContactAddress8', 'paymentMethod8', 'insuranceType8',
    'insuranceNumber8', 'medicalCardNumber8', false, 'bed8', 'wristbandLocation8',
    'patientPose8', 'nursingCareLevel8', 'illnessSeverityLevel8', 'dietType8', 'isolationPrecaution8',
    'chiefComplaint8', 'admin', 'deptNameadmin', 'wardCode8', 'wardName8', 'attendingDoctorId8',
    'primaryCareDoctorId8', 'admittingDoctorId8', 'responsibleNurseId8', 'admissionSourceDeptName8',
    'admissionSourceDeptId8', 'admissionType8', true, '',
    0, now(), now(), 'admittingAccountId8', now(),
    'diagnosis8', 'diagnosisCode8', 'diagnosisTcm8', 'diagnosisTcmCode8', 'diagnosisType8', 'diagnosisAccountId8',
    'dischargedType8', now(), now(), 'dischargedDiagnosis8',
    'dischargedDeptName8', 'dischargedDeptId8', now(), now(), 'dischargingAccountId8',
    now()),
    (9, 'mrn9', 'hisPatientId9', 'hisIndexId9', 'hisPatientSerialNumber9',
    1, now(), 'hisAdmissionDiagnosis9', 'hisBedNumber9',
    false, '', 'icuName9', 1, now(),
    1.84, 65.18, 'weightType9', 'weightIbw9', 'bloodType9', 'bloodRh9', 'pastMedicalHistory9',
    'allergies9', 'phone9', 'homePhone9', 'homeAddress9', 'documentType9', 'idCardNumber9', 'nation9',
    'nativePlace9', 'occupation9', 0, 'emergencyContactName9', 'emergencyContactRelation9',
    'emergencyContactPhone9', 'emergencyContactAddress9', 'paymentMethod9', 'insuranceType9',
    'insuranceNumber9', 'medicalCardNumber9', false, 'bed9', 'wristbandLocation9',
    'patientPose9', 'nursingCareLevel9', 'illnessSeverityLevel9', 'dietType9', 'isolationPrecaution9',
    'chiefComplaint9', 'admin', 'deptNameadmin', 'wardCode9', 'wardName9', 'attendingDoctorId9',
    'primaryCareDoctorId9', 'admittingDoctorId9', 'responsibleNurseId9', 'admissionSourceDeptName9',
    'admissionSourceDeptId9', 'admissionType9', true, '',
    0, now(), now(), 'admittingAccountId9', now(),
    'diagnosis9', 'diagnosisCode9', 'diagnosisTcm9', 'diagnosisTcmCode9', 'diagnosisType9', 'diagnosisAccountId9',
    'dischargedType9', now(), now(), 'dischargedDiagnosis9',
    'dischargedDeptName9', 'dischargedDeptId9', now(), now(), 'dischargingAccountId9',
    now()),
    (10, 'mrn10', 'hisPatientId10', 'hisIndexId10', 'hisPatientSerialNumber10',
    1, now(), 'hisAdmissionDiagnosis10', 'hisBedNumber10',
    false, '', 'icuName10', 1, now(),
    1.85, 65.20, 'weightType10', 'weightIbw10', 'bloodType10', 'bloodRh10', 'pastMedicalHistory10',
    'allergies10', 'phone10', 'homePhone10', 'homeAddress10', 'documentType10', 'idCardNumber10', 'nation10',
    'nativePlace10', 'occupation10', 0, 'emergencyContactName10', 'emergencyContactRelation10',
    'emergencyContactPhone10', 'emergencyContactAddress10', 'paymentMethod10', 'insuranceType10',
    'insuranceNumber10', 'medicalCardNumber10', false, 'bed10', 'wristbandLocation10',
    'patientPose10', 'nursingCareLevel10', 'illnessSeverityLevel10', 'dietType10', 'isolationPrecaution10',
    'chiefComplaint10', 'admin', 'deptNameadmin', 'wardCode10', 'wardName10', 'attendingDoctorId10',
    'primaryCareDoctorId10', 'admittingDoctorId10', 'responsibleNurseId10', 'admissionSourceDeptName10',
    'admissionSourceDeptId10', 'admissionType10', true, '',
    0, now(), now(), 'admittingAccountId10', now(),
    'diagnosis10', 'diagnosisCode10', 'diagnosisTcm10', 'diagnosisTcmCode10', 'diagnosisType10', 'diagnosisAccountId10',
    'dischargedType10', now(), now(), 'dischargedDiagnosis10',
    'dischargedDeptName10', 'dischargedDeptId10', now(), now(), 'dischargingAccountId10',
    now());

INSERT INTO patient_records (
    id, his_mrn, his_patient_id, his_index_id, his_patient_serial_number,
    his_admission_count, his_admission_time, his_admission_diagnosis, his_bed_number,
    icu_manual_entry, icu_manual_entry_account_id, icu_name, icu_gender, icu_date_of_birth,
    height, weight, weight_type, weight_ibw, blood_type, blood_rh, past_medical_history,
    allergies, phone, home_phone, home_address, document_type, id_card_number, nation,
    native_place, occupation, marital_status, emergency_contact_name, emergency_contact_relation,
    emergency_contact_phone, emergency_contact_address, payment_method, insurance_type,
    insurance_number, medical_card_number, is_vip_patient, bed_number_str, wristband_location,
    patient_pose, nursing_care_level, illness_severity_level, diet_type, isolation_precaution,
    chief_complaint, dept_id, dept_name, ward_code, ward_name, attending_doctor_id,
    primary_care_doctor_id, admitting_doctor_id, responsible_nurse_id, admission_source_dept_name,
    admission_source_dept_id, admission_type, is_planned_admission, unplanned_admission_reason,
    admission_status, admission_time, admission_edit_time, admitting_account_id, diagnosis_time,
    diagnosis, diagnosis_code, diagnosis_tcm, diagnosis_tcm_code, diagnosis_type, diagnosis_account_id,
    discharged_type, discharged_death_time, discharged_hospital_exit_time, discharged_diagnosis,
    discharged_dept_name, discharged_dept_id, discharge_time, discharge_edit_time, discharging_account_id,
    created_at
) VALUES
    (11, 'mrn11', 'hisPatientId11', 'hisIndexId11', 'hisPatientSerialNumber11',
    1, now(), 'hisAdmissionDiagnosis11', 'hisBedNumber11',
    false, '', 'icuName11', 1, now(),
    1.76, 65.02, 'weightType11', 'weightIbw11', 'bloodType11', 'bloodRh11', 'pastMedicalHistory11',
    'allergies11', 'phone11', 'homePhone11', 'homeAddress11', 'documentType11', 'idCardNumber11', 'nation11',
    'nativePlace11', 'occupation11', 0, 'emergencyContactName11', 'emergencyContactRelation11',
    'emergencyContactPhone11', 'emergencyContactAddress11', 'paymentMethod11', 'insuranceType11',
    'insuranceNumber11', 'medicalCardNumber11', false, 'bed11', 'wristbandLocation11',
    'patientPose11', 'nursingCareLevel11', 'illnessSeverityLevel11', 'dietType11', 'isolationPrecaution11',
    'chiefComplaint11', 'admin', 'deptNameadmin', 'wardCode11', 'wardName11', 'attendingDoctorId11',
    'primaryCareDoctorId11', 'admittingDoctorId11', 'responsibleNurseId11', 'admissionSourceDeptName11',
    'admissionSourceDeptId11', 'admissionType11', true, '',
    1, now(), now(), 'admittingAccountId11', now(),
    'diagnosis11', 'diagnosisCode11', 'diagnosisTcm11', 'diagnosisTcmCode11', 'diagnosisType11', 'diagnosisAccountId11',
    'dischargedType11', now(), now(), 'dischargedDiagnosis11',
    'dischargedDeptName11', 'dischargedDeptId11', now(), now(), 'dischargingAccountId11',
    now()),
    (12, 'mrn12', 'hisPatientId12', 'hisIndexId12', 'hisPatientSerialNumber12',
    1, now(), 'hisAdmissionDiagnosis12', 'hisBedNumber12',
    false, '', 'icuName12', 1, now(),
    1.77, 65.04, 'weightType12', 'weightIbw12', 'bloodType12', 'bloodRh12', 'pastMedicalHistory12',
    'allergies12', 'phone12', 'homePhone12', 'homeAddress12', 'documentType12', 'idCardNumber12', 'nation12',
    'nativePlace12', 'occupation12', 0, 'emergencyContactName12', 'emergencyContactRelation12',
    'emergencyContactPhone12', 'emergencyContactAddress12', 'paymentMethod12', 'insuranceType12',
    'insuranceNumber12', 'medicalCardNumber12', false, 'bed12', 'wristbandLocation12',
    'patientPose12', 'nursingCareLevel12', 'illnessSeverityLevel12', 'dietType12', 'isolationPrecaution12',
    'chiefComplaint12', 'admin', 'deptNameadmin', 'wardCode12', 'wardName12', 'attendingDoctorId12',
    'primaryCareDoctorId12', 'admittingDoctorId12', 'responsibleNurseId12', 'admissionSourceDeptName12',
    'admissionSourceDeptId12', 'admissionType12', true, '',
    1, now(), now(), 'admittingAccountId12', now(),
    'diagnosis12', 'diagnosisCode12', 'diagnosisTcm12', 'diagnosisTcmCode12', 'diagnosisType12', 'diagnosisAccountId12',
    'dischargedType12', now(), now(), 'dischargedDiagnosis12',
    'dischargedDeptName12', 'dischargedDeptId12', now(), now(), 'dischargingAccountId12',
    now()),
    (13, 'mrn13', 'hisPatientId13', 'hisIndexId13', 'hisPatientSerialNumber13',
    1, now(), 'hisAdmissionDiagnosis13', 'hisBedNumber13',
    false, '', 'icuName13', 1, now(),
    1.78, 65.06, 'weightType13', 'weightIbw13', 'bloodType13', 'bloodRh13', 'pastMedicalHistory13',
    'allergies13', 'phone13', 'homePhone13', 'homeAddress13', 'documentType13', 'idCardNumber13', 'nation13',
    'nativePlace13', 'occupation13', 0, 'emergencyContactName13', 'emergencyContactRelation13',
    'emergencyContactPhone13', 'emergencyContactAddress13', 'paymentMethod13', 'insuranceType13',
    'insuranceNumber13', 'medicalCardNumber13', false, 'bed13', 'wristbandLocation13',
    'patientPose13', 'nursingCareLevel13', 'illnessSeverityLevel13', 'dietType13', 'isolationPrecaution13',
    'chiefComplaint13', 'admin', 'deptNameadmin', 'wardCode13', 'wardName13', 'attendingDoctorId13',
    'primaryCareDoctorId13', 'admittingDoctorId13', 'responsibleNurseId13', 'admissionSourceDeptName13',
    'admissionSourceDeptId13', 'admissionType13', true, '',
    1, now(), now(), 'admittingAccountId13', now(),
    'diagnosis13', 'diagnosisCode13', 'diagnosisTcm13', 'diagnosisTcmCode13', 'diagnosisType13', 'diagnosisAccountId13',
    'dischargedType13', now(), now(), 'dischargedDiagnosis13',
    'dischargedDeptName13', 'dischargedDeptId13', now(), now(), 'dischargingAccountId13',
    now()),
    (14, 'mrn14', 'hisPatientId14', 'hisIndexId14', 'hisPatientSerialNumber14',
    1, now(), 'hisAdmissionDiagnosis14', 'hisBedNumber14',
    false, '', 'icuName14', 1, now(),
    1.79, 65.08, 'weightType14', 'weightIbw14', 'bloodType14', 'bloodRh14', 'pastMedicalHistory14',
    'allergies14', 'phone14', 'homePhone14', 'homeAddress14', 'documentType14', 'idCardNumber14', 'nation14',
    'nativePlace14', 'occupation14', 0, 'emergencyContactName14', 'emergencyContactRelation14',
    'emergencyContactPhone14', 'emergencyContactAddress14', 'paymentMethod14', 'insuranceType14',
    'insuranceNumber14', 'medicalCardNumber14', false, 'bed14', 'wristbandLocation14',
    'patientPose14', 'nursingCareLevel14', 'illnessSeverityLevel14', 'dietType14', 'isolationPrecaution14',
    'chiefComplaint14', 'admin', 'deptNameadmin', 'wardCode14', 'wardName14', 'attendingDoctorId14',
    'primaryCareDoctorId14', 'admittingDoctorId14', 'responsibleNurseId14', 'admissionSourceDeptName14',
    'admissionSourceDeptId14', 'admissionType14', true, '',
    1, now(), now(), 'admittingAccountId14', now(),
    'diagnosis14', 'diagnosisCode14', 'diagnosisTcm14', 'diagnosisTcmCode14', 'diagnosisType14', 'diagnosisAccountId14',
    'dischargedType14', now(), now(), 'dischargedDiagnosis14',
    'dischargedDeptName14', 'dischargedDeptId14', now(), now(), 'dischargingAccountId14',
    now()),
    (15, 'mrn15', 'hisPatientId15', 'hisIndexId15', 'hisPatientSerialNumber15',
    1, now(), 'hisAdmissionDiagnosis15', 'hisBedNumber15',
    false, '', 'icuName15', 1, now(),
    1.80, 65.10, 'weightType15', 'weightIbw15', 'bloodType15', 'bloodRh15', 'pastMedicalHistory15',
    'allergies15', 'phone15', 'homePhone15', 'homeAddress15', 'documentType15', 'idCardNumber15', 'nation15',
    'nativePlace15', 'occupation15', 0, 'emergencyContactName15', 'emergencyContactRelation15',
    'emergencyContactPhone15', 'emergencyContactAddress15', 'paymentMethod15', 'insuranceType15',
    'insuranceNumber15', 'medicalCardNumber15', false, 'bed15', 'wristbandLocation15',
    'patientPose15', 'nursingCareLevel15', 'illnessSeverityLevel15', 'dietType15', 'isolationPrecaution15',
    'chiefComplaint15', 'admin', 'deptNameadmin', 'wardCode15', 'wardName15', 'attendingDoctorId15',
    'primaryCareDoctorId15', 'admittingDoctorId15', 'responsibleNurseId15', 'admissionSourceDeptName15',
    'admissionSourceDeptId15', 'admissionType15', true, '',
    1, now(), now(), 'admittingAccountId15', now(),
    'diagnosis15', 'diagnosisCode15', 'diagnosisTcm15', 'diagnosisTcmCode15', 'diagnosisType15', 'diagnosisAccountId15',
    'dischargedType15', now(), now(), 'dischargedDiagnosis15',
    'dischargedDeptName15', 'dischargedDeptId15', now(), now(), 'dischargingAccountId15',
    now()),
    (16, 'mrn16', 'hisPatientId16', 'hisIndexId16', 'hisPatientSerialNumber16',
    1, now(), 'hisAdmissionDiagnosis16', 'hisBedNumber16',
    false, '', 'icuName16', 1, now(),
    1.81, 65.12, 'weightType16', 'weightIbw16', 'bloodType16', 'bloodRh16', 'pastMedicalHistory16',
    'allergies16', 'phone16', 'homePhone16', 'homeAddress16', 'documentType16', 'idCardNumber16', 'nation16',
    'nativePlace16', 'occupation16', 0, 'emergencyContactName16', 'emergencyContactRelation16',
    'emergencyContactPhone16', 'emergencyContactAddress16', 'paymentMethod16', 'insuranceType16',
    'insuranceNumber16', 'medicalCardNumber16', false, 'bed16', 'wristbandLocation16',
    'patientPose16', 'nursingCareLevel16', 'illnessSeverityLevel16', 'dietType16', 'isolationPrecaution16',
    'chiefComplaint16', 'admin', 'deptNameadmin', 'wardCode16', 'wardName16', 'attendingDoctorId16',
    'primaryCareDoctorId16', 'admittingDoctorId16', 'responsibleNurseId16', 'admissionSourceDeptName16',
    'admissionSourceDeptId16', 'admissionType16', true, '',
    1, now(), now(), 'admittingAccountId16', now(),
    'diagnosis16', 'diagnosisCode16', 'diagnosisTcm16', 'diagnosisTcmCode16', 'diagnosisType16', 'diagnosisAccountId16',
    'dischargedType16', now(), now(), 'dischargedDiagnosis16',
    'dischargedDeptName16', 'dischargedDeptId16', now(), now(), 'dischargingAccountId16',
    now()),
    (17, 'mrn17', 'hisPatientId17', 'hisIndexId17', 'hisPatientSerialNumber17',
    1, now(), 'hisAdmissionDiagnosis17', 'hisBedNumber17',
    false, '', 'icuName17', 1, now(),
    1.82, 65.14, 'weightType17', 'weightIbw17', 'bloodType17', 'bloodRh17', 'pastMedicalHistory17',
    'allergies17', 'phone17', 'homePhone17', 'homeAddress17', 'documentType17', 'idCardNumber17', 'nation17',
    'nativePlace17', 'occupation17', 0, 'emergencyContactName17', 'emergencyContactRelation17',
    'emergencyContactPhone17', 'emergencyContactAddress17', 'paymentMethod17', 'insuranceType17',
    'insuranceNumber17', 'medicalCardNumber17', false, 'bed17', 'wristbandLocation17',
    'patientPose17', 'nursingCareLevel17', 'illnessSeverityLevel17', 'dietType17', 'isolationPrecaution17',
    'chiefComplaint17', 'admin', 'deptNameadmin', 'wardCode17', 'wardName17', 'attendingDoctorId17',
    'primaryCareDoctorId17', 'admittingDoctorId17', 'responsibleNurseId17', 'admissionSourceDeptName17',
    'admissionSourceDeptId17', 'admissionType17', true, '',
    1, now(), now(), 'admittingAccountId17', now(),
    'diagnosis17', 'diagnosisCode17', 'diagnosisTcm17', 'diagnosisTcmCode17', 'diagnosisType17', 'diagnosisAccountId17',
    'dischargedType17', now(), now(), 'dischargedDiagnosis17',
    'dischargedDeptName17', 'dischargedDeptId17', now(), now(), 'dischargingAccountId17',
    now()),
    (18, 'mrn18', 'hisPatientId18', 'hisIndexId18', 'hisPatientSerialNumber18',
    1, now(), 'hisAdmissionDiagnosis18', 'hisBedNumber18',
    false, '', 'icuName18', 1, now(),
    1.83, 65.16, 'weightType18', 'weightIbw18', 'bloodType18', 'bloodRh18', 'pastMedicalHistory18',
    'allergies18', 'phone18', 'homePhone18', 'homeAddress18', 'documentType18', 'idCardNumber18', 'nation18',
    'nativePlace18', 'occupation18', 0, 'emergencyContactName18', 'emergencyContactRelation18',
    'emergencyContactPhone18', 'emergencyContactAddress18', 'paymentMethod18', 'insuranceType18',
    'insuranceNumber18', 'medicalCardNumber18', false, 'bed18', 'wristbandLocation18',
    'patientPose18', 'nursingCareLevel18', 'illnessSeverityLevel18', 'dietType18', 'isolationPrecaution18',
    'chiefComplaint18', 'admin', 'deptNameadmin', 'wardCode18', 'wardName18', 'attendingDoctorId18',
    'primaryCareDoctorId18', 'admittingDoctorId18', 'responsibleNurseId18', 'admissionSourceDeptName18',
    'admissionSourceDeptId18', 'admissionType18', true, '',
    1, now(), now(), 'admittingAccountId18', now(),
    'diagnosis18', 'diagnosisCode18', 'diagnosisTcm18', 'diagnosisTcmCode18', 'diagnosisType18', 'diagnosisAccountId18',
    'dischargedType18', now(), now(), 'dischargedDiagnosis18',
    'dischargedDeptName18', 'dischargedDeptId18', now(), now(), 'dischargingAccountId18',
    now()),
    (19, 'mrn19', 'hisPatientId19', 'hisIndexId19', 'hisPatientSerialNumber19',
    1, now(), 'hisAdmissionDiagnosis19', 'hisBedNumber19',
    false, '', 'icuName19', 1, now(),
    1.84, 65.18, 'weightType19', 'weightIbw19', 'bloodType19', 'bloodRh19', 'pastMedicalHistory19',
    'allergies19', 'phone19', 'homePhone19', 'homeAddress19', 'documentType19', 'idCardNumber19', 'nation19',
    'nativePlace19', 'occupation19', 0, 'emergencyContactName19', 'emergencyContactRelation19',
    'emergencyContactPhone19', 'emergencyContactAddress19', 'paymentMethod19', 'insuranceType19',
    'insuranceNumber19', 'medicalCardNumber19', false, 'bed19', 'wristbandLocation19',
    'patientPose19', 'nursingCareLevel19', 'illnessSeverityLevel19', 'dietType19', 'isolationPrecaution19',
    'chiefComplaint19', 'admin', 'deptNameadmin', 'wardCode19', 'wardName19', 'attendingDoctorId19',
    'primaryCareDoctorId19', 'admittingDoctorId19', 'responsibleNurseId19', 'admissionSourceDeptName19',
    'admissionSourceDeptId19', 'admissionType19', true, '',
    1, now(), now(), 'admittingAccountId19', now(),
    'diagnosis19', 'diagnosisCode19', 'diagnosisTcm19', 'diagnosisTcmCode19', 'diagnosisType19', 'diagnosisAccountId19',
    'dischargedType19', now(), now(), 'dischargedDiagnosis19',
    'dischargedDeptName19', 'dischargedDeptId19', now(), now(), 'dischargingAccountId19',
    now()),
    (20, 'mrn20', 'hisPatientId20', 'hisIndexId20', 'hisPatientSerialNumber20',
    1, now(), 'hisAdmissionDiagnosis20', 'hisBedNumber20',
    false, '', 'icuName20', 1, now(),
    1.85, 65.20, 'weightType20', 'weightIbw20', 'bloodType20', 'bloodRh20', 'pastMedicalHistory20',
    'allergies20', 'phone20', 'homePhone20', 'homeAddress20', 'documentType20', 'idCardNumber20', 'nation20',
    'nativePlace20', 'occupation20', 0, 'emergencyContactName20', 'emergencyContactRelation20',
    'emergencyContactPhone20', 'emergencyContactAddress20', 'paymentMethod20', 'insuranceType20',
    'insuranceNumber20', 'medicalCardNumber20', false, 'bed20', 'wristbandLocation20',
    'patientPose20', 'nursingCareLevel20', 'illnessSeverityLevel20', 'dietType20', 'isolationPrecaution20',
    'chiefComplaint20', 'admin', 'deptNameadmin', 'wardCode20', 'wardName20', 'attendingDoctorId20',
    'primaryCareDoctorId20', 'admittingDoctorId20', 'responsibleNurseId20', 'admissionSourceDeptName20',
    'admissionSourceDeptId20', 'admissionType20', true, '',
    1, now(), now(), 'admittingAccountId20', now(),
    'diagnosis20', 'diagnosisCode20', 'diagnosisTcm20', 'diagnosisTcmCode20', 'diagnosisType20', 'diagnosisAccountId20',
    'dischargedType20', now(), now(), 'dischargedDiagnosis20',
    'dischargedDeptName20', 'dischargedDeptId20', now(), now(), 'dischargingAccountId20',
    now());

INSERT INTO patient_records (
    id, his_mrn, his_patient_id, his_index_id, his_patient_serial_number,
    his_admission_count, his_admission_time, his_admission_diagnosis, his_bed_number,
    icu_manual_entry, icu_manual_entry_account_id, icu_name, icu_gender, icu_date_of_birth,
    height, weight, weight_type, weight_ibw, blood_type, blood_rh, past_medical_history,
    allergies, phone, home_phone, home_address, document_type, id_card_number, nation,
    native_place, occupation, marital_status, emergency_contact_name, emergency_contact_relation,
    emergency_contact_phone, emergency_contact_address, payment_method, insurance_type,
    insurance_number, medical_card_number, is_vip_patient, bed_number_str, wristband_location,
    patient_pose, nursing_care_level, illness_severity_level, diet_type, isolation_precaution,
    chief_complaint, dept_id, dept_name, ward_code, ward_name, attending_doctor_id,
    primary_care_doctor_id, admitting_doctor_id, responsible_nurse_id, admission_source_dept_name,
    admission_source_dept_id, admission_type, is_planned_admission, unplanned_admission_reason,
    admission_status, admission_time, admission_edit_time, admitting_account_id, diagnosis_time,
    diagnosis, diagnosis_code, diagnosis_tcm, diagnosis_tcm_code, diagnosis_type, diagnosis_account_id,
    discharged_type, discharged_death_time, discharged_hospital_exit_time, discharged_diagnosis,
    discharged_dept_name, discharged_dept_id, discharge_time, discharge_edit_time, discharging_account_id,
    created_at
) VALUES
    (21, 'mrn21', 'hisPatientId21', 'hisIndexId21', 'hisPatientSerialNumber21',
    1, now(), 'hisAdmissionDiagnosis21', 'hisBedNumber21',
    false, '', 'icuName21', 1, now(),
    1.76, 65.02, 'weightType21', 'weightIbw21', 'bloodType21', 'bloodRh21', 'pastMedicalHistory21',
    'allergies21', 'phone21', 'homePhone21', 'homeAddress21', 'documentType21', 'idCardNumber21', 'nation21',
    'nativePlace21', 'occupation21', 0, 'emergencyContactName21', 'emergencyContactRelation21',
    'emergencyContactPhone21', 'emergencyContactAddress21', 'paymentMethod21', 'insuranceType21',
    'insuranceNumber21', 'medicalCardNumber21', false, 'bed21', 'wristbandLocation21',
    'patientPose21', 'nursingCareLevel21', 'illnessSeverityLevel21', 'dietType21', 'isolationPrecaution21',
    'chiefComplaint21', 'admin', 'deptNameadmin', 'wardCode21', 'wardName21', 'attendingDoctorId21',
    'primaryCareDoctorId21', 'admittingDoctorId21', 'responsibleNurseId21', 'admissionSourceDeptName21',
    'admissionSourceDeptId21', 'admissionType21', true, '',
    2, now(), now(), 'admittingAccountId21', now(),
    'diagnosis21', 'diagnosisCode21', 'diagnosisTcm21', 'diagnosisTcmCode21', 'diagnosisType21', 'diagnosisAccountId21',
    'dischargedType21', now(), now(), 'dischargedDiagnosis21',
    'dischargedDeptName21', 'dischargedDeptId21', now(), now(), 'dischargingAccountId21',
    now()),
    (22, 'mrn22', 'hisPatientId22', 'hisIndexId22', 'hisPatientSerialNumber22',
    1, now(), 'hisAdmissionDiagnosis22', 'hisBedNumber22',
    false, '', 'icuName22', 1, now(),
    1.77, 65.04, 'weightType22', 'weightIbw22', 'bloodType22', 'bloodRh22', 'pastMedicalHistory22',
    'allergies22', 'phone22', 'homePhone22', 'homeAddress22', 'documentType22', 'idCardNumber22', 'nation22',
    'nativePlace22', 'occupation22', 0, 'emergencyContactName22', 'emergencyContactRelation22',
    'emergencyContactPhone22', 'emergencyContactAddress22', 'paymentMethod22', 'insuranceType22',
    'insuranceNumber22', 'medicalCardNumber22', false, 'bed22', 'wristbandLocation22',
    'patientPose22', 'nursingCareLevel22', 'illnessSeverityLevel22', 'dietType22', 'isolationPrecaution22',
    'chiefComplaint22', 'admin', 'deptNameadmin', 'wardCode22', 'wardName22', 'attendingDoctorId22',
    'primaryCareDoctorId22', 'admittingDoctorId22', 'responsibleNurseId22', 'admissionSourceDeptName22',
    'admissionSourceDeptId22', 'admissionType22', true, '',
    2, now(), now(), 'admittingAccountId22', now(),
    'diagnosis22', 'diagnosisCode22', 'diagnosisTcm22', 'diagnosisTcmCode22', 'diagnosisType22', 'diagnosisAccountId22',
    'dischargedType22', now(), now(), 'dischargedDiagnosis22',
    'dischargedDeptName22', 'dischargedDeptId22', now(), now(), 'dischargingAccountId22',
    now()),
    (23, 'mrn23', 'hisPatientId23', 'hisIndexId23', 'hisPatientSerialNumber23',
    1, now(), 'hisAdmissionDiagnosis23', 'hisBedNumber23',
    false, '', 'icuName23', 1, now(),
    1.78, 65.06, 'weightType23', 'weightIbw23', 'bloodType23', 'bloodRh23', 'pastMedicalHistory23',
    'allergies23', 'phone23', 'homePhone23', 'homeAddress23', 'documentType23', 'idCardNumber23', 'nation23',
    'nativePlace23', 'occupation23', 0, 'emergencyContactName23', 'emergencyContactRelation23',
    'emergencyContactPhone23', 'emergencyContactAddress23', 'paymentMethod23', 'insuranceType23',
    'insuranceNumber23', 'medicalCardNumber23', false, 'bed23', 'wristbandLocation23',
    'patientPose23', 'nursingCareLevel23', 'illnessSeverityLevel23', 'dietType23', 'isolationPrecaution23',
    'chiefComplaint23', 'admin', 'deptNameadmin', 'wardCode23', 'wardName23', 'attendingDoctorId23',
    'primaryCareDoctorId23', 'admittingDoctorId23', 'responsibleNurseId23', 'admissionSourceDeptName23',
    'admissionSourceDeptId23', 'admissionType23', true, '',
    2, now(), now(), 'admittingAccountId23', now(),
    'diagnosis23', 'diagnosisCode23', 'diagnosisTcm23', 'diagnosisTcmCode23', 'diagnosisType23', 'diagnosisAccountId23',
    'dischargedType23', now(), now(), 'dischargedDiagnosis23',
    'dischargedDeptName23', 'dischargedDeptId23', now(), now(), 'dischargingAccountId23',
    now()),
    (24, 'mrn24', 'hisPatientId24', 'hisIndexId24', 'hisPatientSerialNumber24',
    1, now(), 'hisAdmissionDiagnosis24', 'hisBedNumber24',
    false, '', 'icuName24', 1, now(),
    1.79, 65.08, 'weightType24', 'weightIbw24', 'bloodType24', 'bloodRh24', 'pastMedicalHistory24',
    'allergies24', 'phone24', 'homePhone24', 'homeAddress24', 'documentType24', 'idCardNumber24', 'nation24',
    'nativePlace24', 'occupation24', 0, 'emergencyContactName24', 'emergencyContactRelation24',
    'emergencyContactPhone24', 'emergencyContactAddress24', 'paymentMethod24', 'insuranceType24',
    'insuranceNumber24', 'medicalCardNumber24', false, 'bed24', 'wristbandLocation24',
    'patientPose24', 'nursingCareLevel24', 'illnessSeverityLevel24', 'dietType24', 'isolationPrecaution24',
    'chiefComplaint24', 'admin', 'deptNameadmin', 'wardCode24', 'wardName24', 'attendingDoctorId24',
    'primaryCareDoctorId24', 'admittingDoctorId24', 'responsibleNurseId24', 'admissionSourceDeptName24',
    'admissionSourceDeptId24', 'admissionType24', true, '',
    2, now(), now(), 'admittingAccountId24', now(),
    'diagnosis24', 'diagnosisCode24', 'diagnosisTcm24', 'diagnosisTcmCode24', 'diagnosisType24', 'diagnosisAccountId24',
    'dischargedType24', now(), now(), 'dischargedDiagnosis24',
    'dischargedDeptName24', 'dischargedDeptId24', now(), now(), 'dischargingAccountId24',
    now()),
    (25, 'mrn25', 'hisPatientId25', 'hisIndexId25', 'hisPatientSerialNumber25',
    1, now(), 'hisAdmissionDiagnosis25', 'hisBedNumber25',
    false, '', 'icuName25', 1, now(),
    1.80, 65.10, 'weightType25', 'weightIbw25', 'bloodType25', 'bloodRh25', 'pastMedicalHistory25',
    'allergies25', 'phone25', 'homePhone25', 'homeAddress25', 'documentType25', 'idCardNumber25', 'nation25',
    'nativePlace25', 'occupation25', 0, 'emergencyContactName25', 'emergencyContactRelation25',
    'emergencyContactPhone25', 'emergencyContactAddress25', 'paymentMethod25', 'insuranceType25',
    'insuranceNumber25', 'medicalCardNumber25', false, 'bed25', 'wristbandLocation25',
    'patientPose25', 'nursingCareLevel25', 'illnessSeverityLevel25', 'dietType25', 'isolationPrecaution25',
    'chiefComplaint25', 'admin', 'deptNameadmin', 'wardCode25', 'wardName25', 'attendingDoctorId25',
    'primaryCareDoctorId25', 'admittingDoctorId25', 'responsibleNurseId25', 'admissionSourceDeptName25',
    'admissionSourceDeptId25', 'admissionType25', true, '',
    2, now(), now(), 'admittingAccountId25', now(),
    'diagnosis25', 'diagnosisCode25', 'diagnosisTcm25', 'diagnosisTcmCode25', 'diagnosisType25', 'diagnosisAccountId25',
    'dischargedType25', now(), now(), 'dischargedDiagnosis25',
    'dischargedDeptName25', 'dischargedDeptId25', now(), now(), 'dischargingAccountId25',
    now()),
    (26, 'mrn26', 'hisPatientId26', 'hisIndexId26', 'hisPatientSerialNumber26',
    1, now(), 'hisAdmissionDiagnosis26', 'hisBedNumber26',
    false, '', 'icuName26', 1, now(),
    1.81, 65.12, 'weightType26', 'weightIbw26', 'bloodType26', 'bloodRh26', 'pastMedicalHistory26',
    'allergies26', 'phone26', 'homePhone26', 'homeAddress26', 'documentType26', 'idCardNumber26', 'nation26',
    'nativePlace26', 'occupation26', 0, 'emergencyContactName26', 'emergencyContactRelation26',
    'emergencyContactPhone26', 'emergencyContactAddress26', 'paymentMethod26', 'insuranceType26',
    'insuranceNumber26', 'medicalCardNumber26', false, 'bed26', 'wristbandLocation26',
    'patientPose26', 'nursingCareLevel26', 'illnessSeverityLevel26', 'dietType26', 'isolationPrecaution26',
    'chiefComplaint26', 'admin', 'deptNameadmin', 'wardCode26', 'wardName26', 'attendingDoctorId26',
    'primaryCareDoctorId26', 'admittingDoctorId26', 'responsibleNurseId26', 'admissionSourceDeptName26',
    'admissionSourceDeptId26', 'admissionType26', true, '',
    2, now(), now(), 'admittingAccountId26', now(),
    'diagnosis26', 'diagnosisCode26', 'diagnosisTcm26', 'diagnosisTcmCode26', 'diagnosisType26', 'diagnosisAccountId26',
    'dischargedType26', now(), now(), 'dischargedDiagnosis26',
    'dischargedDeptName26', 'dischargedDeptId26', now(), now(), 'dischargingAccountId26',
    now()),
    (27, 'mrn27', 'hisPatientId27', 'hisIndexId27', 'hisPatientSerialNumber27',
    1, now(), 'hisAdmissionDiagnosis27', 'hisBedNumber27',
    false, '', 'icuName27', 1, now(),
    1.82, 65.14, 'weightType27', 'weightIbw27', 'bloodType27', 'bloodRh27', 'pastMedicalHistory27',
    'allergies27', 'phone27', 'homePhone27', 'homeAddress27', 'documentType27', 'idCardNumber27', 'nation27',
    'nativePlace27', 'occupation27', 0, 'emergencyContactName27', 'emergencyContactRelation27',
    'emergencyContactPhone27', 'emergencyContactAddress27', 'paymentMethod27', 'insuranceType27',
    'insuranceNumber27', 'medicalCardNumber27', false, 'bed27', 'wristbandLocation27',
    'patientPose27', 'nursingCareLevel27', 'illnessSeverityLevel27', 'dietType27', 'isolationPrecaution27',
    'chiefComplaint27', 'admin', 'deptNameadmin', 'wardCode27', 'wardName27', 'attendingDoctorId27',
    'primaryCareDoctorId27', 'admittingDoctorId27', 'responsibleNurseId27', 'admissionSourceDeptName27',
    'admissionSourceDeptId27', 'admissionType27', true, '',
    2, now(), now(), 'admittingAccountId27', now(),
    'diagnosis27', 'diagnosisCode27', 'diagnosisTcm27', 'diagnosisTcmCode27', 'diagnosisType27', 'diagnosisAccountId27',
    'dischargedType27', now(), now(), 'dischargedDiagnosis27',
    'dischargedDeptName27', 'dischargedDeptId27', now(), now(), 'dischargingAccountId27',
    now()),
    (28, 'mrn28', 'hisPatientId28', 'hisIndexId28', 'hisPatientSerialNumber28',
    1, now(), 'hisAdmissionDiagnosis28', 'hisBedNumber28',
    false, '', 'icuName28', 1, now(),
    1.83, 65.16, 'weightType28', 'weightIbw28', 'bloodType28', 'bloodRh28', 'pastMedicalHistory28',
    'allergies28', 'phone28', 'homePhone28', 'homeAddress28', 'documentType28', 'idCardNumber28', 'nation28',
    'nativePlace28', 'occupation28', 0, 'emergencyContactName28', 'emergencyContactRelation28',
    'emergencyContactPhone28', 'emergencyContactAddress28', 'paymentMethod28', 'insuranceType28',
    'insuranceNumber28', 'medicalCardNumber28', false, 'bed28', 'wristbandLocation28',
    'patientPose28', 'nursingCareLevel28', 'illnessSeverityLevel28', 'dietType28', 'isolationPrecaution28',
    'chiefComplaint28', 'admin', 'deptNameadmin', 'wardCode28', 'wardName28', 'attendingDoctorId28',
    'primaryCareDoctorId28', 'admittingDoctorId28', 'responsibleNurseId28', 'admissionSourceDeptName28',
    'admissionSourceDeptId28', 'admissionType28', true, '',
    2, now(), now(), 'admittingAccountId28', now(),
    'diagnosis28', 'diagnosisCode28', 'diagnosisTcm28', 'diagnosisTcmCode28', 'diagnosisType28', 'diagnosisAccountId28',
    'dischargedType28', now(), now(), 'dischargedDiagnosis28',
    'dischargedDeptName28', 'dischargedDeptId28', now(), now(), 'dischargingAccountId28',
    now()),
    (29, 'mrn29', 'hisPatientId29', 'hisIndexId29', 'hisPatientSerialNumber29',
    1, now(), 'hisAdmissionDiagnosis29', 'hisBedNumber29',
    false, '', 'icuName29', 1, now(),
    1.84, 65.18, 'weightType29', 'weightIbw29', 'bloodType29', 'bloodRh29', 'pastMedicalHistory29',
    'allergies29', 'phone29', 'homePhone29', 'homeAddress29', 'documentType29', 'idCardNumber29', 'nation29',
    'nativePlace29', 'occupation29', 0, 'emergencyContactName29', 'emergencyContactRelation29',
    'emergencyContactPhone29', 'emergencyContactAddress29', 'paymentMethod29', 'insuranceType29',
    'insuranceNumber29', 'medicalCardNumber29', false, 'bed29', 'wristbandLocation29',
    'patientPose29', 'nursingCareLevel29', 'illnessSeverityLevel29', 'dietType29', 'isolationPrecaution29',
    'chiefComplaint29', 'admin', 'deptNameadmin', 'wardCode29', 'wardName29', 'attendingDoctorId29',
    'primaryCareDoctorId29', 'admittingDoctorId29', 'responsibleNurseId29', 'admissionSourceDeptName29',
    'admissionSourceDeptId29', 'admissionType29', true, '',
    2, now(), now(), 'admittingAccountId29', now(),
    'diagnosis29', 'diagnosisCode29', 'diagnosisTcm29', 'diagnosisTcmCode29', 'diagnosisType29', 'diagnosisAccountId29',
    'dischargedType29', now(), now(), 'dischargedDiagnosis29',
    'dischargedDeptName29', 'dischargedDeptId29', now(), now(), 'dischargingAccountId29',
    now()),
    (30, 'mrn30', 'hisPatientId30', 'hisIndexId30', 'hisPatientSerialNumber30',
    1, now(), 'hisAdmissionDiagnosis30', 'hisBedNumber30',
    false, '', 'icuName30', 1, now(),
    1.85, 65.20, 'weightType30', 'weightIbw30', 'bloodType30', 'bloodRh30', 'pastMedicalHistory30',
    'allergies30', 'phone30', 'homePhone30', 'homeAddress30', 'documentType30', 'idCardNumber30', 'nation30',
    'nativePlace30', 'occupation30', 0, 'emergencyContactName30', 'emergencyContactRelation30',
    'emergencyContactPhone30', 'emergencyContactAddress30', 'paymentMethod30', 'insuranceType30',
    'insuranceNumber30', 'medicalCardNumber30', false, 'bed30', 'wristbandLocation30',
    'patientPose30', 'nursingCareLevel30', 'illnessSeverityLevel30', 'dietType30', 'isolationPrecaution30',
    'chiefComplaint30', 'admin', 'deptNameadmin', 'wardCode30', 'wardName30', 'attendingDoctorId30',
    'primaryCareDoctorId30', 'admittingDoctorId30', 'responsibleNurseId30', 'admissionSourceDeptName30',
    'admissionSourceDeptId30', 'admissionType30', true, '',
    2, now(), now(), 'admittingAccountId30', now(),
    'diagnosis30', 'diagnosisCode30', 'diagnosisTcm30', 'diagnosisTcmCode30', 'diagnosisType30', 'diagnosisAccountId30',
    'dischargedType30', now(), now(), 'dischargedDiagnosis30',
    'dischargedDeptName30', 'dischargedDeptId30', now(), now(), 'dischargingAccountId30',
    now());

INSERT INTO patient_records (
    id, his_mrn, his_patient_id, his_index_id, his_patient_serial_number,
    his_admission_count, his_admission_time, his_admission_diagnosis, his_bed_number,
    icu_manual_entry, icu_manual_entry_account_id, icu_name, icu_gender, icu_date_of_birth,
    height, weight, weight_type, weight_ibw, blood_type, blood_rh, past_medical_history,
    allergies, phone, home_phone, home_address, document_type, id_card_number, nation,
    native_place, occupation, marital_status, emergency_contact_name, emergency_contact_relation,
    emergency_contact_phone, emergency_contact_address, payment_method, insurance_type,
    insurance_number, medical_card_number, is_vip_patient, bed_number_str, wristband_location,
    patient_pose, nursing_care_level, illness_severity_level, diet_type, isolation_precaution,
    chief_complaint, dept_id, dept_name, ward_code, ward_name, attending_doctor_id,
    primary_care_doctor_id, admitting_doctor_id, responsible_nurse_id, admission_source_dept_name,
    admission_source_dept_id, admission_type, is_planned_admission, unplanned_admission_reason,
    admission_status, admission_time, admission_edit_time, admitting_account_id, diagnosis_time,
    diagnosis, diagnosis_code, diagnosis_tcm, diagnosis_tcm_code, diagnosis_type, diagnosis_account_id,
    discharged_type, discharged_death_time, discharged_hospital_exit_time, discharged_diagnosis,
    discharged_dept_name, discharged_dept_id, discharge_time, discharge_edit_time, discharging_account_id,
    created_at
) VALUES
    (31, 'mrn31', 'hisPatientId31', 'hisIndexId31', 'hisPatientSerialNumber31',
    1, now(), 'hisAdmissionDiagnosis31', 'hisBedNumber31',
    false, '', 'icuName31', 1, now(),
    1.76, 65.02, 'weightType31', 'weightIbw31', 'bloodType31', 'bloodRh31', 'pastMedicalHistory31',
    'allergies31', 'phone31', 'homePhone31', 'homeAddress31', 'documentType31', 'idCardNumber31', 'nation31',
    'nativePlace31', 'occupation31', 0, 'emergencyContactName31', 'emergencyContactRelation31',
    'emergencyContactPhone31', 'emergencyContactAddress31', 'paymentMethod31', 'insuranceType31',
    'insuranceNumber31', 'medicalCardNumber31', false, 'bed31', 'wristbandLocation31',
    'patientPose31', 'nursingCareLevel31', 'illnessSeverityLevel31', 'dietType31', 'isolationPrecaution31',
    'chiefComplaint31', 'admin', 'deptNameadmin', 'wardCode31', 'wardName31', 'attendingDoctorId31',
    'primaryCareDoctorId31', 'admittingDoctorId31', 'responsibleNurseId31', 'admissionSourceDeptName31',
    'admissionSourceDeptId31', 'admissionType31', true, '',
    3, now(), now(), 'admittingAccountId31', now(),
    'diagnosis31', 'diagnosisCode31', 'diagnosisTcm31', 'diagnosisTcmCode31', 'diagnosisType31', 'diagnosisAccountId31',
    'dischargedType31', now(), now(), 'dischargedDiagnosis31',
    'dischargedDeptName31', 'dischargedDeptId31', now(), now(), 'dischargingAccountId31',
    now()),
    (32, 'mrn32', 'hisPatientId32', 'hisIndexId32', 'hisPatientSerialNumber32',
    1, now(), 'hisAdmissionDiagnosis32', 'hisBedNumber32',
    false, '', 'icuName32', 1, now(),
    1.77, 65.04, 'weightType32', 'weightIbw32', 'bloodType32', 'bloodRh32', 'pastMedicalHistory32',
    'allergies32', 'phone32', 'homePhone32', 'homeAddress32', 'documentType32', 'idCardNumber32', 'nation32',
    'nativePlace32', 'occupation32', 0, 'emergencyContactName32', 'emergencyContactRelation32',
    'emergencyContactPhone32', 'emergencyContactAddress32', 'paymentMethod32', 'insuranceType32',
    'insuranceNumber32', 'medicalCardNumber32', false, 'bed32', 'wristbandLocation32',
    'patientPose32', 'nursingCareLevel32', 'illnessSeverityLevel32', 'dietType32', 'isolationPrecaution32',
    'chiefComplaint32', 'admin', 'deptNameadmin', 'wardCode32', 'wardName32', 'attendingDoctorId32',
    'primaryCareDoctorId32', 'admittingDoctorId32', 'responsibleNurseId32', 'admissionSourceDeptName32',
    'admissionSourceDeptId32', 'admissionType32', true, '',
    3, now(), now(), 'admittingAccountId32', now(),
    'diagnosis32', 'diagnosisCode32', 'diagnosisTcm32', 'diagnosisTcmCode32', 'diagnosisType32', 'diagnosisAccountId32',
    'dischargedType32', now(), now(), 'dischargedDiagnosis32',
    'dischargedDeptName32', 'dischargedDeptId32', now(), now(), 'dischargingAccountId32',
    now()),
    (33, 'mrn33', 'hisPatientId33', 'hisIndexId33', 'hisPatientSerialNumber33',
    1, now(), 'hisAdmissionDiagnosis33', 'hisBedNumber33',
    false, '', 'icuName33', 1, now(),
    1.78, 65.06, 'weightType33', 'weightIbw33', 'bloodType33', 'bloodRh33', 'pastMedicalHistory33',
    'allergies33', 'phone33', 'homePhone33', 'homeAddress33', 'documentType33', 'idCardNumber33', 'nation33',
    'nativePlace33', 'occupation33', 0, 'emergencyContactName33', 'emergencyContactRelation33',
    'emergencyContactPhone33', 'emergencyContactAddress33', 'paymentMethod33', 'insuranceType33',
    'insuranceNumber33', 'medicalCardNumber33', false, 'bed33', 'wristbandLocation33',
    'patientPose33', 'nursingCareLevel33', 'illnessSeverityLevel33', 'dietType33', 'isolationPrecaution33',
    'chiefComplaint33', 'admin', 'deptNameadmin', 'wardCode33', 'wardName33', 'attendingDoctorId33',
    'primaryCareDoctorId33', 'admittingDoctorId33', 'responsibleNurseId33', 'admissionSourceDeptName33',
    'admissionSourceDeptId33', 'admissionType33', true, '',
    3, now(), now(), 'admittingAccountId33', now(),
    'diagnosis33', 'diagnosisCode33', 'diagnosisTcm33', 'diagnosisTcmCode33', 'diagnosisType33', 'diagnosisAccountId33',
    'dischargedType33', now(), now(), 'dischargedDiagnosis33',
    'dischargedDeptName33', 'dischargedDeptId33', now(), now(), 'dischargingAccountId33',
    now()),
    (34, 'mrn34', 'hisPatientId34', 'hisIndexId34', 'hisPatientSerialNumber34',
    1, now(), 'hisAdmissionDiagnosis34', 'hisBedNumber34',
    false, '', 'icuName34', 1, now(),
    1.79, 65.08, 'weightType34', 'weightIbw34', 'bloodType34', 'bloodRh34', 'pastMedicalHistory34',
    'allergies34', 'phone34', 'homePhone34', 'homeAddress34', 'documentType34', 'idCardNumber34', 'nation34',
    'nativePlace34', 'occupation34', 0, 'emergencyContactName34', 'emergencyContactRelation34',
    'emergencyContactPhone34', 'emergencyContactAddress34', 'paymentMethod34', 'insuranceType34',
    'insuranceNumber34', 'medicalCardNumber34', false, 'bed34', 'wristbandLocation34',
    'patientPose34', 'nursingCareLevel34', 'illnessSeverityLevel34', 'dietType34', 'isolationPrecaution34',
    'chiefComplaint34', 'admin', 'deptNameadmin', 'wardCode34', 'wardName34', 'attendingDoctorId34',
    'primaryCareDoctorId34', 'admittingDoctorId34', 'responsibleNurseId34', 'admissionSourceDeptName34',
    'admissionSourceDeptId34', 'admissionType34', true, '',
    3, now(), now(), 'admittingAccountId34', now(),
    'diagnosis34', 'diagnosisCode34', 'diagnosisTcm34', 'diagnosisTcmCode34', 'diagnosisType34', 'diagnosisAccountId34',
    'dischargedType34', now(), now(), 'dischargedDiagnosis34',
    'dischargedDeptName34', 'dischargedDeptId34', now(), now(), 'dischargingAccountId34',
    now()),
    (35, 'mrn35', 'hisPatientId35', 'hisIndexId35', 'hisPatientSerialNumber35',
    1, now(), 'hisAdmissionDiagnosis35', 'hisBedNumber35',
    false, '', 'icuName35', 1, now(),
    1.80, 65.10, 'weightType35', 'weightIbw35', 'bloodType35', 'bloodRh35', 'pastMedicalHistory35',
    'allergies35', 'phone35', 'homePhone35', 'homeAddress35', 'documentType35', 'idCardNumber35', 'nation35',
    'nativePlace35', 'occupation35', 0, 'emergencyContactName35', 'emergencyContactRelation35',
    'emergencyContactPhone35', 'emergencyContactAddress35', 'paymentMethod35', 'insuranceType35',
    'insuranceNumber35', 'medicalCardNumber35', false, 'bed35', 'wristbandLocation35',
    'patientPose35', 'nursingCareLevel35', 'illnessSeverityLevel35', 'dietType35', 'isolationPrecaution35',
    'chiefComplaint35', 'admin', 'deptNameadmin', 'wardCode35', 'wardName35', 'attendingDoctorId35',
    'primaryCareDoctorId35', 'admittingDoctorId35', 'responsibleNurseId35', 'admissionSourceDeptName35',
    'admissionSourceDeptId35', 'admissionType35', true, '',
    3, now(), now(), 'admittingAccountId35', now(),
    'diagnosis35', 'diagnosisCode35', 'diagnosisTcm35', 'diagnosisTcmCode35', 'diagnosisType35', 'diagnosisAccountId35',
    'dischargedType35', now(), now(), 'dischargedDiagnosis35',
    'dischargedDeptName35', 'dischargedDeptId35', now(), now(), 'dischargingAccountId35',
    now()),
    (36, 'mrn36', 'hisPatientId36', 'hisIndexId36', 'hisPatientSerialNumber36',
    1, now(), 'hisAdmissionDiagnosis36', 'hisBedNumber36',
    false, '', 'icuName36', 1, now(),
    1.81, 65.12, 'weightType36', 'weightIbw36', 'bloodType36', 'bloodRh36', 'pastMedicalHistory36',
    'allergies36', 'phone36', 'homePhone36', 'homeAddress36', 'documentType36', 'idCardNumber36', 'nation36',
    'nativePlace36', 'occupation36', 0, 'emergencyContactName36', 'emergencyContactRelation36',
    'emergencyContactPhone36', 'emergencyContactAddress36', 'paymentMethod36', 'insuranceType36',
    'insuranceNumber36', 'medicalCardNumber36', false, 'bed36', 'wristbandLocation36',
    'patientPose36', 'nursingCareLevel36', 'illnessSeverityLevel36', 'dietType36', 'isolationPrecaution36',
    'chiefComplaint36', 'admin', 'deptNameadmin', 'wardCode36', 'wardName36', 'attendingDoctorId36',
    'primaryCareDoctorId36', 'admittingDoctorId36', 'responsibleNurseId36', 'admissionSourceDeptName36',
    'admissionSourceDeptId36', 'admissionType36', true, '',
    3, now(), now(), 'admittingAccountId36', now(),
    'diagnosis36', 'diagnosisCode36', 'diagnosisTcm36', 'diagnosisTcmCode36', 'diagnosisType36', 'diagnosisAccountId36',
    'dischargedType36', now(), now(), 'dischargedDiagnosis36',
    'dischargedDeptName36', 'dischargedDeptId36', now(), now(), 'dischargingAccountId36',
    now()),
    (37, 'mrn37', 'hisPatientId37', 'hisIndexId37', 'hisPatientSerialNumber37',
    1, now(), 'hisAdmissionDiagnosis37', 'hisBedNumber37',
    false, '', 'icuName37', 1, now(),
    1.82, 65.14, 'weightType37', 'weightIbw37', 'bloodType37', 'bloodRh37', 'pastMedicalHistory37',
    'allergies37', 'phone37', 'homePhone37', 'homeAddress37', 'documentType37', 'idCardNumber37', 'nation37',
    'nativePlace37', 'occupation37', 0, 'emergencyContactName37', 'emergencyContactRelation37',
    'emergencyContactPhone37', 'emergencyContactAddress37', 'paymentMethod37', 'insuranceType37',
    'insuranceNumber37', 'medicalCardNumber37', false, 'bed37', 'wristbandLocation37',
    'patientPose37', 'nursingCareLevel37', 'illnessSeverityLevel37', 'dietType37', 'isolationPrecaution37',
    'chiefComplaint37', 'admin', 'deptNameadmin', 'wardCode37', 'wardName37', 'attendingDoctorId37',
    'primaryCareDoctorId37', 'admittingDoctorId37', 'responsibleNurseId37', 'admissionSourceDeptName37',
    'admissionSourceDeptId37', 'admissionType37', true, '',
    3, now(), now(), 'admittingAccountId37', now(),
    'diagnosis37', 'diagnosisCode37', 'diagnosisTcm37', 'diagnosisTcmCode37', 'diagnosisType37', 'diagnosisAccountId37',
    'dischargedType37', now(), now(), 'dischargedDiagnosis37',
    'dischargedDeptName37', 'dischargedDeptId37', now(), now(), 'dischargingAccountId37',
    now()),
    (38, 'mrn38', 'hisPatientId38', 'hisIndexId38', 'hisPatientSerialNumber38',
    1, now(), 'hisAdmissionDiagnosis38', 'hisBedNumber38',
    false, '', 'icuName38', 1, now(),
    1.83, 65.16, 'weightType38', 'weightIbw38', 'bloodType38', 'bloodRh38', 'pastMedicalHistory38',
    'allergies38', 'phone38', 'homePhone38', 'homeAddress38', 'documentType38', 'idCardNumber38', 'nation38',
    'nativePlace38', 'occupation38', 0, 'emergencyContactName38', 'emergencyContactRelation38',
    'emergencyContactPhone38', 'emergencyContactAddress38', 'paymentMethod38', 'insuranceType38',
    'insuranceNumber38', 'medicalCardNumber38', false, 'bed38', 'wristbandLocation38',
    'patientPose38', 'nursingCareLevel38', 'illnessSeverityLevel38', 'dietType38', 'isolationPrecaution38',
    'chiefComplaint38', 'admin', 'deptNameadmin', 'wardCode38', 'wardName38', 'attendingDoctorId38',
    'primaryCareDoctorId38', 'admittingDoctorId38', 'responsibleNurseId38', 'admissionSourceDeptName38',
    'admissionSourceDeptId38', 'admissionType38', true, '',
    3, now(), now(), 'admittingAccountId38', now(),
    'diagnosis38', 'diagnosisCode38', 'diagnosisTcm38', 'diagnosisTcmCode38', 'diagnosisType38', 'diagnosisAccountId38',
    'dischargedType38', now(), now(), 'dischargedDiagnosis38',
    'dischargedDeptName38', 'dischargedDeptId38', now(), now(), 'dischargingAccountId38',
    now()),
    (39, 'mrn39', 'hisPatientId39', 'hisIndexId39', 'hisPatientSerialNumber39',
    1, now(), 'hisAdmissionDiagnosis39', 'hisBedNumber39',
    false, '', 'icuName39', 1, now(),
    1.84, 65.18, 'weightType39', 'weightIbw39', 'bloodType39', 'bloodRh39', 'pastMedicalHistory39',
    'allergies39', 'phone39', 'homePhone39', 'homeAddress39', 'documentType39', 'idCardNumber39', 'nation39',
    'nativePlace39', 'occupation39', 0, 'emergencyContactName39', 'emergencyContactRelation39',
    'emergencyContactPhone39', 'emergencyContactAddress39', 'paymentMethod39', 'insuranceType39',
    'insuranceNumber39', 'medicalCardNumber39', false, 'bed39', 'wristbandLocation39',
    'patientPose39', 'nursingCareLevel39', 'illnessSeverityLevel39', 'dietType39', 'isolationPrecaution39',
    'chiefComplaint39', 'admin', 'deptNameadmin', 'wardCode39', 'wardName39', 'attendingDoctorId39',
    'primaryCareDoctorId39', 'admittingDoctorId39', 'responsibleNurseId39', 'admissionSourceDeptName39',
    'admissionSourceDeptId39', 'admissionType39', true, '',
    3, now(), now(), 'admittingAccountId39', now(),
    'diagnosis39', 'diagnosisCode39', 'diagnosisTcm39', 'diagnosisTcmCode39', 'diagnosisType39', 'diagnosisAccountId39',
    'dischargedType39', now(), now(), 'dischargedDiagnosis39',
    'dischargedDeptName39', 'dischargedDeptId39', now(), now(), 'dischargingAccountId39',
    now()),
    (40, 'mrn40', 'hisPatientId40', 'hisIndexId40', 'hisPatientSerialNumber40',
    1, now(), 'hisAdmissionDiagnosis40', 'hisBedNumber40',
    false, '', 'icuName40', 1, now(),
    1.85, 65.20, 'weightType40', 'weightIbw40', 'bloodType40', 'bloodRh40', 'pastMedicalHistory40',
    'allergies40', 'phone40', 'homePhone40', 'homeAddress40', 'documentType40', 'idCardNumber40', 'nation40',
    'nativePlace40', 'occupation40', 0, 'emergencyContactName40', 'emergencyContactRelation40',
    'emergencyContactPhone40', 'emergencyContactAddress40', 'paymentMethod40', 'insuranceType40',
    'insuranceNumber40', 'medicalCardNumber40', false, 'bed40', 'wristbandLocation40',
    'patientPose40', 'nursingCareLevel40', 'illnessSeverityLevel40', 'dietType40', 'isolationPrecaution40',
    'chiefComplaint40', 'admin', 'deptNameadmin', 'wardCode40', 'wardName40', 'attendingDoctorId40',
    'primaryCareDoctorId40', 'admittingDoctorId40', 'responsibleNurseId40', 'admissionSourceDeptName40',
    'admissionSourceDeptId40', 'admissionType40', true, '',
    3, now(), now(), 'admittingAccountId40', now(),
    'diagnosis40', 'diagnosisCode40', 'diagnosisTcm40', 'diagnosisTcmCode40', 'diagnosisType40', 'diagnosisAccountId40',
    'dischargedType40', now(), now(), 'dischargedDiagnosis40',
    'dischargedDeptName40', 'dischargedDeptId40', now(), now(), 'dischargingAccountId40',
    now());